_select_data:
  column-sizes:
    col-6: One Half
    col-12: Full Width
    col-4: One Third
    col-3: One Quarter
    col-6_sm-6: One Half (Mobile Half Responsive)
    col-4_sm-6: One Third (Mobile Half Responsive)
    col-3_sm-6: One Quarter (Mobile Half Responsive)
    col-4_sm-6_xs-12: One Third (Mobile Half, XS Full Width Responsive)