seo: 
  site_name: 
  title: 
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark_color: '#122143'
  light_color: '#F4DB97'
  light-subtle_color: '#f8eac2'
  primary-font: 'Inconsolata', monospace;
